### ISSUE TITLE
TypeError: AST identifier must be of type str

### ISSUE THREAD

**Issue by jfrydendall** [jlowin/pyautodiff#5]
Hi I have found an error within two of the examples - svm.py and tracing.py

I have installed Theano from trunk through pip and installed the latest pyautodiff from git.  Everything seems to be installed correctly. However, when I run the examples I get the following error from svm.py

~/build/pyautodiff/autodiff/examples$ python3 svm.py
Traceback (most recent call last):
  File "svm.py", line 43, in <module>
    test_svm()
  File "svm.py", line 33, in test_svm
    w, b = fmin_l_bfgs_b(loss_fn, init_args=(w_0, b_0))
  File "/usr/local/lib/python3.4/dist-packages/autodiff/optimize.py", line 111, in fmin_l_bfgs_b
    gradient=True)
  File "/usr/local/lib/python3.4/dist-packages/autodiff/symbolic.py", line 510, in **init**
    escape_on_error=escape_on_error)
  File "/usr/local/lib/python3.4/dist-packages/autodiff/symbolic.py", line 53, in **init**
    self._symfn = self.context.recompile(self.pyfn)
  File "/usr/local/lib/python3.4/dist-packages/autodiff/context.py", line 236, in recompile
    globals=f_globals)
  File "/usr/local/lib/python3.4/dist-packages/meta/decompiler/__init__.py", line 57, in compile_func
    code = compile(module, filename, 'exec')
TypeError: AST identifier must be of type str

and from tracing.py

~/build/pyautodiff/autodiff/examples$ python3 tracing.py
Traceback (most recent call last):
  File "tracing.py", line 21, in <module>
    tracer = Symbolic()
TypeError: **init**() missing 1 required positional argument: 'pyfn'

I am on a ubuntu 14.04_amd64 with python 3.4.

Can you please advise me how to proceed from here? Is the development of pyautudiff on hold or will there updates in the future?

Best Regards,

Jan Frydendall

**Comment by jlowin** [comment]
Jan, thank you for identifying this issue. I didn't experience it until I upgraded to Python 3.4. The cause isn't immediately obvious, but I am trying to figure it out.

**Comment by jlowin** [comment]
@jfrydendall thanks for catching this. The SVM/tracing examples hadn't been updated with the rest (the SVM one in particular wouldn't even run under Python 3)! The issue was with the handling of _varargs and *_kwargs in nested functions (which are used in the optimization routines). I'm running a few more checks to see if this created any related issues.

**Comment by jfrydendall** [comment]
I still have issues with the svm.py example, after the latest update:

pyautodiff/autodiff/examples$ python3 svm.py
Traceback (most recent call last):
  File "svm.py", line 43, in <module>
    test_svm()
  File "svm.py", line 33, in test_svm
    w, b = fmin_l_bfgs_b(loss_fn, init_args=(w_0, b_0))
  File "/usr/local/lib/python3.4/dist-packages/autodiff/optimize.py", line
111, in fmin_l_bfgs_b
    gradient=True)
  File "/usr/local/lib/python3.4/dist-packages/autodiff/symbolic.py", line
512, in **init**
    _, (sym_vector, result) = symbolic.trace(_init_args, *_init_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autodiff/symbolic.py", line
104, in trace
    results = self.symfn(_c_args, *_c_kwargs)
  File "<Context-AST>", line 501, in wrapper
  File "<Context-AST>", line 543, in args_from_vector
  File "/usr/local/lib/python3.4/dist-packages/autodiff/context.py", line
993, in reshape
    return var.reshape(_args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/theano/tensor/var.py", line
297, in reshape
    return theano.tensor.basic.reshape(self, shape, ndim=ndim)
  File "/usr/local/lib/python3.4/dist-packages/theano/tensor/basic.py",
line 3870, in reshape
    ndim = get_vector_length(newshape)
  File "/usr/local/lib/python3.4/dist-packages/theano/tensor/basic.py",
line 3642, in get_vector_length
    raise TypeError('argument must be symbol

I don't know if it has something to do with the latest change you made to
context.py?

2014-08-16 16:28 GMT+02:00 Jeremiah Lowin notifications@github.com:

**Comment by jlowin** [comment]
@jfrydendall one of the changes I made was too aggressive. Please give it another shot. I apologize for the difficulty you're having!

**Comment by jfrydendall** [comment]
Great - I can confirm that all examples work again with Python 3.4 on
Ubuntu 14.04 amd 64.
Thank you

2014-08-20 10:21 GMT+02:00 Jeremiah Lowin notifications@github.com:
